version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: walletdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  wallet-api:
    build:
      context: .
      dockerfile: WalletApi/Dockerfile
    container_name: wallet-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=walletdb;Username=postgres;Password=password
    entrypoint: ["sh", "-c", "sleep 5 && dotnet WalletApi.dll"]

volumes:
  pgdata:


